<?php

namespace ContainerGN4kBVl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBienTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BienType' shared autowired service.
     *
     * @return \App\Form\BienType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BienType.php';

        return $container->privates['App\\Form\\BienType'] = new \App\Form\BienType();
    }
}
