<?php

namespace ContainerRHG1Ov5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NU8rkKwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nU8rkKw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nU8rkKw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bien' => ['privates', '.errored..service_locator.nU8rkKw.App\\Entity\\Bien', NULL, 'Cannot autowire service ".service_locator.nU8rkKw": it references class "App\\Entity\\Bien" but no such service exists.'],
            'bienRepository' => ['privates', 'App\\Repository\\BienRepository', 'getBienRepositoryService', true],
        ], [
            'bien' => 'App\\Entity\\Bien',
            'bienRepository' => 'App\\Repository\\BienRepository',
        ]);
    }
}
