<?php

namespace ContainerRHG1Ov5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6TL8PjFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6TL8PjF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6TL8PjF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bienRepository' => ['privates', 'App\\Repository\\BienRepository', 'getBienRepositoryService', true],
        ], [
            'bienRepository' => 'App\\Repository\\BienRepository',
        ]);
    }
}
