<?php

namespace ContainerRHG1Ov5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDompdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Dompdf\Dompdf' shared autowired service.
     *
     * @return \Dompdf\Dompdf
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dompdf/dompdf/src/Dompdf.php';

        return $container->privates['Dompdf\\Dompdf'] = new \Dompdf\Dompdf(['isHtml5ParserEnabled' => true, 'isPhpEnabled' => true]);
    }
}
