<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRHG1Ov5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRHG1Ov5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRHG1Ov5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRHG1Ov5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRHG1Ov5\App_KernelDevDebugContainer([
    'container.build_hash' => 'RHG1Ov5',
    'container.build_id' => '5a06617f',
    'container.build_time' => 1699965662,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRHG1Ov5');
