<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/1.47ff13b9.js',
                '/build/app.191d3dbe.js',
            ],
            'css' => [
                '/build/app.e87c93e8.css',
            ],
        ],
    ],
],

]];
